allowBuilds:
  '@ast-grep/lang-yaml': true
  esbuild: true
  msw: true

minimumReleaseAgeExclude:
  - esbuild@0.28.1
  - jsondiffpatch@0.7.2
  - '@hono/node-server@2.0.5'

overrides:
  '@hono/node-server@<2.0.5': 2.0.11
  esbuild@<=0.24.2: 0.28.1
  esbuild@>=0.27.3 <0.28.1: 0.28.1
  jsondiffpatch@<0.7.2: 0.7.6
  solid-js: '1.9.14'
