on:
  push:
    branches:
      - main
  pull_request:

name: build

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.3
        with:
          fetch-depth: 0
      - uses: moonrepo/setup-toolchain@v0.6.4
      - uses: pnpm/action-setup@v5.0.0
        with:
          run_install: false
      - uses: actions/setup-node@v6.4.0
        with:
          node-version: '24.17.0'
          cache: 'pnpm'
      - run: pnpm install
      - uses: actions/cache@v5.1.0
        with:
          path: .moon/cache
          key: ${{ runner.os }}-moon
      - run: pnpm build
